trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: TestParallel1
jobs:
- job: TestJob1
  steps:
  - script: echo "Running TestJob1"
    displayName: 'Run TestJob1'

- stage: TestParallel2
jobs:
- job: TestJob2
  steps:
  - script: echo "Running TestJob2"
    displayName: 'Run TestJob2'